### ISSUE TITLE
Bug when building GenericLauncher with AIDE

### ISSUE THREAD

**Issue by jose-vm** [byteandahalf/GenericLauncher#2] opened 2014-08-06 02:04 UTC
I tried building this project with AIDE, and it says they are mistakes on this project. I tried to fix them, but that didn't helped.

**Comment by artus9033** [comment] 2015-02-15 12:42
Reproduced the bug.

**Comment by sliceofcode** [comment] 2015-02-16 01:46
I wouldn't recommend using AIDE as your primary development environment, typing on a computer is much faster and it is harder to debug problems on AIDE because it is significantly different from the usual Android SDK and NDK.

**Comment by artus9033** [comment] 2015-02-16 06:08
Yes, but aide is helpful. I fixed the bug. Move the class with error to src/com/mojang/minecraftpe.

**Comment by artus9033** [comment] 2015-02-16 06:09
@sliceofcode, you can close the issue.

**Comment by sliceofcode** [comment] 2015-02-16 07:17
This isn't my issue.

**Comment by artus9033** [comment] 2015-02-18 08:20
So whose issue is this?

**Comment by sliceofcode** [comment] 2015-02-20 06:09
@jose-vm

**Comment by artus9033** [comment] 2015-02-20 14:50
Ok, sorry.

**Closed** 2015-02-21 01:19 UTC
